# Generated by Django 5.1.7 on 2025-03-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='articles',
        ),
    ]
